### ISSUE TITLE
No Projects listed

### ISSUE THREAD

**Issue by trickidicki** [adam-cowley/neo4j-desktop-vue#2]
On Windows, running Neo4J Desktop 1.0.22 (neo4j@bolt://localhost:7687)
Trying to load the Projects list, an error is logged in the Console:
`Uncaught (in promise) Error: `this.$neo4j.desktop` functions can only be used within Neo4j Desktop`

Any ideas?

**Comment by adam-cowley** [comment]
This error will throw when `window.neo4jDesktopApi` is not defined.  Are you running the app outside of Neo4j Desktop development mode (ie through Chrome)?

**Comment by trickidicki** [comment]
Ah, that's what the problem was. Couldn't tell from the docs...
Thanks!
